backend:
  name: git-gateway
  repo: thetechnohack/winuxdroid
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts" # Used in the UI
    folder: "content/posts"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string"
        }

      - {
          label: "Date",
          name: "date",
          widget: "datetime"
        }

      - {
          label: "Description",
          name: "description",
          widget: "string" 
        }

      - {
          label: "Authors",
          name: "author",
          widget: "list",
          default: "Admin"
        }

      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false 
        }

      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: false,
        }

      - label: "Cover"
        name: "cover"
        collapse: true
        widget: "object"
        fields:
          - {
              label: "Image",
              name: "image",
              widget: "image"
            }
          - {
              label: "Caption",
              name: "caption",
              widget: "string"
            }
          - {
              label: "Alt text",
              name: "alt",
              widget: "string",
              required: true
            }
          - {
              label: "Relative",
              name: "relative",
              widget: "boolean"
              required: false
            }
          - {
              label: "Responsive image",
              name: "responsiveImages",
              widget: "boolean"
              required: false
            }
          - {
              label: "Hide cover",
              name: "hidden",
              widget: "boolean"
              default: false
            }

      - {
          label: "Body",
          name: "body",
          widget: "markdown"
        }

      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/categories.md"
        label: "Categories"
        name: "categories"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/tags.md"
        label: "Tags"
        name: "tags"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/links.md"
        label: "Links"
        name: "links"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
